#ifndef OPENTUI_YOGA_VOCABULARY_H
#define OPENTUI_YOGA_VOCABULARY_H

#include "../include/opentui.h"
#include <yoga/YGEnums.h>

/* Keep the checked vocabulary tied to the Yoga values passed across the bridge. */
#define OT_CHECK_YOGA(OT, YG) static_assert(OT == YG, "Checked layout vocabulary differs from Yoga: " #OT)
OT_CHECK_YOGA(OT_DIRECTION_INHERIT, YGDirectionInherit);
OT_CHECK_YOGA(OT_DIRECTION_LTR, YGDirectionLTR);
OT_CHECK_YOGA(OT_DIRECTION_RTL, YGDirectionRTL);
OT_CHECK_YOGA(OT_FLEX_DIRECTION_COLUMN, YGFlexDirectionColumn);
OT_CHECK_YOGA(OT_FLEX_DIRECTION_COLUMN_REVERSE, YGFlexDirectionColumnReverse);
OT_CHECK_YOGA(OT_FLEX_DIRECTION_ROW, YGFlexDirectionRow);
OT_CHECK_YOGA(OT_FLEX_DIRECTION_ROW_REVERSE, YGFlexDirectionRowReverse);
OT_CHECK_YOGA(OT_JUSTIFY_FLEX_START, YGJustifyFlexStart);
OT_CHECK_YOGA(OT_JUSTIFY_CENTER, YGJustifyCenter);
OT_CHECK_YOGA(OT_JUSTIFY_FLEX_END, YGJustifyFlexEnd);
OT_CHECK_YOGA(OT_JUSTIFY_SPACE_BETWEEN, YGJustifySpaceBetween);
OT_CHECK_YOGA(OT_JUSTIFY_SPACE_AROUND, YGJustifySpaceAround);
OT_CHECK_YOGA(OT_JUSTIFY_SPACE_EVENLY, YGJustifySpaceEvenly);
OT_CHECK_YOGA(OT_ALIGN_AUTO, YGAlignAuto);
OT_CHECK_YOGA(OT_ALIGN_FLEX_START, YGAlignFlexStart);
OT_CHECK_YOGA(OT_ALIGN_CENTER, YGAlignCenter);
OT_CHECK_YOGA(OT_ALIGN_FLEX_END, YGAlignFlexEnd);
OT_CHECK_YOGA(OT_ALIGN_STRETCH, YGAlignStretch);
OT_CHECK_YOGA(OT_ALIGN_BASELINE, YGAlignBaseline);
OT_CHECK_YOGA(OT_ALIGN_SPACE_BETWEEN, YGAlignSpaceBetween);
OT_CHECK_YOGA(OT_ALIGN_SPACE_AROUND, YGAlignSpaceAround);
OT_CHECK_YOGA(OT_ALIGN_SPACE_EVENLY, YGAlignSpaceEvenly);
OT_CHECK_YOGA(OT_POSITION_STATIC, YGPositionTypeStatic);
OT_CHECK_YOGA(OT_POSITION_RELATIVE, YGPositionTypeRelative);
OT_CHECK_YOGA(OT_POSITION_ABSOLUTE, YGPositionTypeAbsolute);
OT_CHECK_YOGA(OT_FLEX_WRAP_NONE, YGWrapNoWrap);
OT_CHECK_YOGA(OT_FLEX_WRAP_WRAP, YGWrapWrap);
OT_CHECK_YOGA(OT_FLEX_WRAP_REVERSE, YGWrapWrapReverse);
OT_CHECK_YOGA(OT_OVERFLOW_VISIBLE, YGOverflowVisible);
OT_CHECK_YOGA(OT_OVERFLOW_HIDDEN, YGOverflowHidden);
OT_CHECK_YOGA(OT_OVERFLOW_SCROLL, YGOverflowScroll);
OT_CHECK_YOGA(OT_DISPLAY_FLEX, YGDisplayFlex);
OT_CHECK_YOGA(OT_DISPLAY_NONE, YGDisplayNone);
OT_CHECK_YOGA(OT_BOX_SIZING_BORDER_BOX, YGBoxSizingBorderBox);
OT_CHECK_YOGA(OT_BOX_SIZING_CONTENT_BOX, YGBoxSizingContentBox);
OT_CHECK_YOGA(OT_UNIT_UNDEFINED, YGUnitUndefined);
OT_CHECK_YOGA(OT_UNIT_POINT, YGUnitPoint);
OT_CHECK_YOGA(OT_UNIT_PERCENT, YGUnitPercent);
OT_CHECK_YOGA(OT_UNIT_AUTO, YGUnitAuto);
OT_CHECK_YOGA(OT_EDGE_LEFT, YGEdgeLeft);
OT_CHECK_YOGA(OT_EDGE_TOP, YGEdgeTop);
OT_CHECK_YOGA(OT_EDGE_RIGHT, YGEdgeRight);
OT_CHECK_YOGA(OT_EDGE_BOTTOM, YGEdgeBottom);
OT_CHECK_YOGA(OT_EDGE_START, YGEdgeStart);
OT_CHECK_YOGA(OT_EDGE_END, YGEdgeEnd);
OT_CHECK_YOGA(OT_EDGE_HORIZONTAL, YGEdgeHorizontal);
OT_CHECK_YOGA(OT_EDGE_VERTICAL, YGEdgeVertical);
OT_CHECK_YOGA(OT_EDGE_ALL, YGEdgeAll);
OT_CHECK_YOGA(OT_GUTTER_COLUMN, YGGutterColumn);
OT_CHECK_YOGA(OT_GUTTER_ROW, YGGutterRow);
OT_CHECK_YOGA(OT_GUTTER_ALL, YGGutterAll);
OT_CHECK_YOGA(OT_DIMENSION_WIDTH, YGDimensionWidth);
OT_CHECK_YOGA(OT_DIMENSION_HEIGHT, YGDimensionHeight);
OT_CHECK_YOGA(OT_MEASURE_UNDEFINED, YGMeasureModeUndefined);
OT_CHECK_YOGA(OT_MEASURE_EXACTLY, YGMeasureModeExactly);
OT_CHECK_YOGA(OT_MEASURE_AT_MOST, YGMeasureModeAtMost);
#undef OT_CHECK_YOGA

#endif
